#!/bin/zsh

set -eu

dir="$(dirname "$(realpath "$0")")"

url="$1"

function get()
{
	if [[ "$1" == https://* ]]
	then
		curl -sSL "$1"
	else
		cat "$1"
	fi
}


tempdir="$(mktemp -d)"
trap "rm -r \"$tempdir\" >& /dev/null" EXIT

get "$url" \
	| htmlq --text 'script[type="application/ld+json"]' \
	| jq -c --arg 'source' "$url" -f "$dir/ld_json.jq" \
	| while IFS=$'\n' read -r recipe
	do
		recipe_id="$(uuidgen -r)"
		tempfile="$tempdir/$recipe_id.yaml"

		echo "$recipe" | yq -Poy | sed -E 's/ (g|l|ml) /\1 /' > "$tempfile"

		nvim-qt --nofork -- "$tempfile"
		[ ! -s "$tempfile" ] && continue

		mv -i "$tempfile" ~/.apsa/library/"$recipe_id.yaml"
	done
apsa -i
